# use Ganache's forked mainnet mode as the default network (mainnet-fork)
# NOTE: You don't *have* to do this, but it is often helpful for testing
# for this repo, we use both base-dev-fork and base-anvil-fork
networks:
  default: base-dev-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.6
  - OpenZeppelin/openzeppelin-contracts@4.9.3

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version:
    remappings:
      - "@yearnvaults=yearn/yearn-vaults@0.4.6"
      - "@openzeppelin/contracts@4.9.3=OpenZeppelin/openzeppelin-contracts@4.9.3/contracts"

reports:
  exclude_contracts:
    - Ownable2Step
    - ERC20
